### PR TITLE
#55 seatcomposition

### PR DESCRIPTION
**Pull request by ArthiRagothaman**
As mentioned corrected the seat layout.

### CODE REVIEW

**Comment by TheDoplarEffect** [comment]
I'm sorry, I thought this issue had to include making the seats clicable.
This PR is just getting the layouts of the seats to match the figma file.
The seatSquares components is just a placeholder

**Review by ReallyBoard123 — CHANGES_REQUESTED** [review]
where did you get access to the file SeatSquares from?

**Comment by ArthiRagothaman** [comment]
Issue#60 SeatSquares used this for my SeatComposition layout

**Comment by ReallyBoard123** [comment]
> Issue#60 SeatSquares used this for my SeatComposition layout

is this ready for PR? please resolve the merge conflicts before.

**Comment by ArthiRagothaman** [comment]
Resolved conflicts.

**Pull request merged**
